In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import string
from wordcloud import wordcloud
import spacy

In [2]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.7.1
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 73.6 MB/s eta 0:00:00
Requirement already satisfied: spacy<3.8.0,>=3.7.2 in /usr/local/lib/python3.10/dist-packages (from en-core-web-sm==3.7.1) (3.7.5)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.12.5)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (4.66.6)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.9.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.1.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (75.1.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (24.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.4.1)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.26.4)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.10/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.2.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.23.4)
Requirement already satisfied: typing-extensions>=4.6.1 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2024.8.30)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (13.9.3)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.20.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (7.0.5)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.0.2)
Requirement already satisfied: marisa-trie>=0.7.7 in /usr/local/lib/python3.10/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.18.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.10/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.16.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.1.2)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [5]:
blogs=pd.read_csv('blogs.csv')
blogs

                                                   Data              Labels
0     Path: cantaloupe.srv.cs.cmu.edu!magnesium.club...         alt.atheism
1     Newsgroups: alt.atheism\nPath: cantaloupe.srv....         alt.atheism
2     Path: cantaloupe.srv.cs.cmu.edu!das-news.harva...         alt.atheism
3     Path: cantaloupe.srv.cs.cmu.edu!magnesium.club...         alt.atheism
4     Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:53...         alt.atheism
...                                                 ...                 ...
1995  Xref: cantaloupe.srv.cs.cmu.edu talk.abortion:...  talk.religion.misc
1996  Xref: cantaloupe.srv.cs.cmu.edu talk.religion....  talk.religion.misc
1997  Xref: cantaloupe.srv.cs.cmu.edu talk.origins:4...  talk.religion.misc
1998  Xref: cantaloupe.srv.cs.cmu.edu talk.religion....  talk.religion.misc
1999  Xref: cantaloupe.srv.cs.cmu.edu sci.skeptic:43...  talk.religion.misc

[2000 rows x 2 columns]

## Removing unwanted text

In [ ]:
import re

# Define a function to remove unwanted text
def clean_text(text):
  """
  Cleans the input text by removing header information and other unwanted parts.
  """
  text = re.sub(r"Xref:.+\n", "", text) # remove Xref line
  text = re.sub(r"Path:.+\n", "", text) # remove Path line
  text = re.sub(r"From:.+\n", "", text) # remove From line
  text = re.sub(r"Newsgroups:.+\n", "", text) # remove Newsgroups line
  text = re.sub(r"Subject:.+\n", "", text) # remove Subject line
  text = re.sub(r"Date:.+\n", "", text) # remove Date line
  text = re.sub(r"Organization:.+\n", "", text) # remove Organization line
  text = re.sub(r"Lines:.+\n", "", text) # remove Lines line
  text = re.sub(r"Message-ID:.+\n", "", text) # remove Message-ID line
  text = re.sub(r"References:.+\n", "", text) # remove References line
  text = re.sub(r"NNTP-Posting-Host:.+\n", "", text) # remove NNTP-Posting-Host line
  text = re.sub(r"In-reply-to:.+\n", "", text) # remove In-reply-to line
  text = re.sub(r"Distribution:.+\n", "", text) # remove Distribution line
  text = re.sub(r"Sender:.+\n", "", text) # remove Sender line

  # remove multiple newlines
  text = re.sub(r"\n+", "\n", text)

  text = text.strip()

  return text


data = blogs['Data'].apply(clean_text)

In [11]:
data

0       In article <1r76ek$7uo@fido.asd.sgi.com> lives...
1       Nntp-Posting-Host: okcforum.osrhe.edu\nX-Newsr...
2       Keywords: slander calumny\nIn article <1993Apr...
3       In article <930420.105805.0x8.rusnews.w165w@ma...
4       Reply-To: eczcaw@mips.nott.ac.uk (C.Wainwright...
                              ...
1995    In article <930422.113807.7Q9.rusnews.w165w@ma...
1996    In article <C5wIA1.4Hr@apollo.hp.com> goykhman...
1997    Reply-To: scharle@lukasiewicz.cc.nd.edu (schar...
1998    Followup-To: talk.religion.misc,alt.sex.storie...
1999    Followup-To: sci.skeptic,talk.politics.misc,ta...
Name: Data, Length: 2000, dtype: object

In [47]:
def clean_text1(text):
    '''Make text lowercase, remove text in square brackets, remove punctuation and remove words containing numbers.'''
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\w*\d\w*', '', text)
    text = re.sub("[0-9" "]+"," ",text)
    text = re.sub('[‘’“”…]', '', text)
    return text

data = data.apply(lambda x: clean_text1(x))

In [48]:
text_data="".join(data)
text_data[:1000]

'in article  liveseysolntzewpdsgicom jon livesey writes\nin article   frank odwyer writes\n in article  liveseysolntzewpdsgicom jon livesey writes\n \n noting that a particular society in this case the mainland uk\n has few religously motivated murders and few murders of any\n kind says very little about whether interreligion murders elsewhere\n are religiously motivated\n \n no but it allows one to conclude that there is nothing inherent\n in all religion or for that matter in catholicism and protestantism\n that motivates one to kill\n\nmotivates or allows    the christian bible says that one may kill\nunder certain circumstances   in fact it instructs one to kill under\ncertain circumstances     \nid say the majority of people have a moral system that instructs them\nto kill under certain circumstances  i do get your distinction between\nmotivate and allow and i do agree that if a flavour of theism allows\natoricities then thats an indictment of that theism  but it rather\ndepends on what the certain ci'

## Removing Punctuation

In [49]:
no_pun_text=text_data.translate(str.maketrans('','',string.punctuation))
no_pun_text[:1000]

'in article  liveseysolntzewpdsgicom jon livesey writes\nin article   frank odwyer writes\n in article  liveseysolntzewpdsgicom jon livesey writes\n \n noting that a particular society in this case the mainland uk\n has few religously motivated murders and few murders of any\n kind says very little about whether interreligion murders elsewhere\n are religiously motivated\n \n no but it allows one to conclude that there is nothing inherent\n in all religion or for that matter in catholicism and protestantism\n that motivates one to kill\n\nmotivates or allows    the christian bible says that one may kill\nunder certain circumstances   in fact it instructs one to kill under\ncertain circumstances     \nid say the majority of people have a moral system that instructs them\nto kill under certain circumstances  i do get your distinction between\nmotivate and allow and i do agree that if a flavour of theism allows\natoricities then thats an indictment of that theism  but it rather\ndepends on what the certain ci'

In [50]:
#Stopwords
import nltk
from nltk.corpus import stopwords
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [51]:
#Tokenization
from nltk.tokenize import word_tokenize
text_tokens = word_tokenize(no_pun_text)
print(text_tokens[0:50])

['in', 'article', 'liveseysolntzewpdsgicom', 'jon', 'livesey', 'writes', 'in', 'article', 'frank', 'odwyer', 'writes', 'in', 'article', 'liveseysolntzewpdsgicom', 'jon', 'livesey', 'writes', 'noting', 'that', 'a', 'particular', 'society', 'in', 'this', 'case', 'the', 'mainland', 'uk', 'has', 'few', 'religously', 'motivated', 'murders', 'and', 'few', 'murders', 'of', 'any', 'kind', 'says', 'very', 'little', 'about', 'whether', 'interreligion', 'murders', 'elsewhere', 'are', 'religiously', 'motivated']

In [52]:
len(text_tokens)

509385

In [53]:
#Remove stopwords
import nltk
nltk.download('stopwords')

my_stop_words = stopwords.words('english')
my_stop_words.append('the')
no_stop_tokens = [word for word in text_tokens if not word in my_stop_words]
print(no_stop_tokens[0:40])

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

['article', 'liveseysolntzewpdsgicom', 'jon', 'livesey', 'writes', 'article', 'frank', 'odwyer', 'writes', 'article', 'liveseysolntzewpdsgicom', 'jon', 'livesey', 'writes', 'noting', 'particular', 'society', 'case', 'mainland', 'uk', 'religously', 'motivated', 'murders', 'murders', 'kind', 'says', 'little', 'whether', 'interreligion', 'murders', 'elsewhere', 'religiously', 'motivated', 'allows', 'one', 'conclude', 'nothing', 'inherent', 'religion', 'matter']

In [54]:
len(no_stop_tokens)

279289

In [55]:
#Noramalize the data
lower_words = [x.lower() for x in no_stop_tokens]
print(lower_words[0:25])

['article', 'liveseysolntzewpdsgicom', 'jon', 'livesey', 'writes', 'article', 'frank', 'odwyer', 'writes', 'article', 'liveseysolntzewpdsgicom', 'jon', 'livesey', 'writes', 'noting', 'particular', 'society', 'case', 'mainland', 'uk', 'religously', 'motivated', 'murders', 'murders', 'kind']

In [56]:
#Stemming
from nltk.stem import PorterStemmer
ps = PorterStemmer()
stemmed_tokens = [ps.stem(word) for word in lower_words]
print(stemmed_tokens[0:40])

['articl', 'liveseysolntzewpdsgicom', 'jon', 'livesey', 'write', 'articl', 'frank', 'odwyer', 'write', 'articl', 'liveseysolntzewpdsgicom', 'jon', 'livesey', 'write', 'note', 'particular', 'societi', 'case', 'mainland', 'uk', 'relig', 'motiv', 'murder', 'murder', 'kind', 'say', 'littl', 'whether', 'interreligion', 'murder', 'elsewher', 'religi', 'motiv', 'allow', 'one', 'conclud', 'noth', 'inher', 'religion', 'matter']

In [57]:
# NLP english language model of spacy library
nlp = spacy.load('en_core_web_sm')
nlp.max_length = 3000000
doc = nlp(' '.join(no_stop_tokens))
print(doc[0:40])

article liveseysolntzewpdsgicom jon livesey writes article frank odwyer writes article liveseysolntzewpdsgicom jon livesey writes noting particular society case mainland uk religously motivated murders murders kind says little whether interreligion murders elsewhere religiously motivated allows one conclude nothing inherent religion matter

In [58]:
# Lemmatizing
lemmas = [token.lemma_ for token in doc]
print(lemmas[0:25])

['article', 'liveseysolntzewpdsgicom', 'jon', 'livesey', 'write', 'article', 'frank', 'odwyer', 'write', 'article', 'liveseysolntzewpdsgicom', 'jon', 'livesey', 'write', 'note', 'particular', 'society', 'case', 'mainland', 'uk', 'religously', 'motivate', 'murder', 'murder', 'kind']

## Feature Extraction

In [ ]:
# count vectoriser tells the frequency of a word.
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
vectorizer = CountVectorizer(min_df = 1, max_df = 0.9)
X = vectorizer.fit_transform(data)
word_freq_df = pd.DataFrame({'term': vectorizer.get_feature_names_out(), 'occurrences':np.asarray(X.sum(axis=0)).ravel().tolist()})
word_freq_df['frequency'] = word_freq_df['occurrences']/np.sum(word_freq_df['occurrences'])

In [61]:
word_freq_df.sort_values('occurrences', ascending = False).head(10)

       term  occurrences  frequency
32086    to        13279   0.028705
22016    of        11880   0.025681
1217    and        10635   0.022990
15179    in         8953   0.019354
16039    is         7829   0.016924
31623  that         7042   0.015223
16117    it         5468   0.011820
11792   for         4920   0.010636
35627   you         4795   0.010365
22169    on         3750   0.008106

The Above words are the most frequent terms form the blogs

## Using TFIDF

In [ ]:
#TFIDF - Term frequency inverse Document Frequencyt
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(stop_words='english', max_features= 1000, max_df = 0.5, smooth_idf=True) 
doc_vec = vectorizer.fit_transform(data)
names_features = vectorizer.get_feature_names_out()
dense = doc_vec.todense()
denselist = dense.tolist()
df = pd.DataFrame(denselist, columns = names_features)

In [63]:
df

,able,absolute,absolutely,accept,access,according,account,act,action,actions,...,yeah,year,years,yes,york,youd,youll,young,youre,youve
0,0.0,0.000000,0.0,0.055214,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.046509,0.0,0.061381,0.0,0.0,0.000000,0.058889
1,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000
2,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.105509,...,0.325156,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.080791,0.000000
3,0.0,0.028363,0.0,0.023338,0.0,0.0,0.026076,0.024582,0.122912,0.099567,...,0.000000,0.018242,0.017402,0.117954,0.0,0.000000,0.0,0.0,0.000000,0.000000
4,0.0,0.000000,0.0,0.227266,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.056487,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.044127,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.070578,0.0,0.000000,0.0,0.0,0.034214,0.089364
1996,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000
1997,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000
1998,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000
1999,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.088302,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000

## N-Gram

In [ ]:
#Bi-gram
def get_top_n2_words(corpus, n=None):
    vec1 = CountVectorizer(ngram_range=(2,2),
            max_features=2000).fit(corpus)
    bag_of_words = vec1.transform(corpus)
    sum_words = bag_of_words.sum(axis=0)
    words_freq = [(word, sum_words[0, idx]) for word, idx in
                  vec1.vocabulary_.items()]
    words_freq =sorted(words_freq, key = lambda x: x[1],
                reverse=True)
    return words_freq[:n]

In [65]:
top2_words = get_top_n2_words(data, n=200) #top 200
top2_df = pd.DataFrame(top2_words)
top2_df.columns=["Bi-gram", "Freq"]
top2_df.head()

      Bi-gram  Freq
0      of the  2777
1      in the  1912
2  in article  1157
3      to the  1134
4      on the  1098

In [66]:
#Tri-gram
def get_top_n3_words(corpus, n=None):
    vec1 = CountVectorizer(ngram_range=(3,3),
           max_features=2000).fit(corpus)
    bag_of_words = vec1.transform(corpus)
    sum_words = bag_of_words.sum(axis=0)
    words_freq = [(word, sum_words[0, idx]) for word, idx in
                  vec1.vocabulary_.items()]
    words_freq =sorted(words_freq, key = lambda x: x[1],
                reverse=True)
    return words_freq[:n]

top3_words = get_top_n3_words(data, n=200)
top3_df = pd.DataFrame(top3_words)
top3_df.columns=["Tri-gram", "Freq"]

In [67]:
top3_df

              Tri-gram  Freq
0    writes in article   322
1           one of the   139
2          there is no   135
3           be able to    97
4        the fact that    90
..                 ...   ...
195        that is not    21
196        of the most    21
197     of the turkish    21
198    to believe that    20
199       there are no    20

[200 rows x 2 columns]

By using N-gram method these are the most frequent words from the blog posts.

## Naive Bayes

In [83]:
blogs_df=pd.DataFrame({'Data':data,'Labels':blogs['Labels']})
blogs_df

                                                   Data              Labels
0     in article  liveseysolntzewpdsgicom jon livese...         alt.atheism
1     nntppostinghost okcforumosrheedu\nxnewsreader ...         alt.atheism
2     keywords slander calumny\nin article  rashid w...         alt.atheism
3     in article  mathew mathewmantiscouk writes\n j...         alt.atheism
4     replyto eczcawmipsnottacuk cwainwright\nin art...         alt.atheism
...                                                 ...                 ...
1995  in article  mathew mathewmantiscouk writes\n f...  talk.religion.misc
1996  in article  goykhmanapollohpcom red herring wr...  talk.religion.misc
1997  replyto scharlelukasiewiczccndedu scharle\nin ...  talk.religion.misc
1998  followupto talkreligionmiscaltsexstoriesaltsex...  talk.religion.misc
1999  followupto sciskeptictalkpoliticsmisctalkrelig...  talk.religion.misc

[2000 rows x 2 columns]

## Train Test Split

In [84]:
from sklearn.model_selection import train_test_split

blog_train,blog_test = train_test_split(blogs_df,test_size=0.3)

In [85]:
blog_train.shape

(1400, 2)

In [74]:
def split_into_words(i):
    return (i.split(" "))

In [ ]:
blogs_bow = CountVectorizer(analyzer=split_into_words).fit(blogs_df.Data)

In [ ]:
# For training blogs
train_blogs_matrix = blogs_bow.transform(blog_train.Data)
train_blogs_matrix.shape

# For testing blogs
test_blogs_matrix = blogs_bow.transform(blog_test.Data)
test_blogs_matrix.shape

(600, 65257)

In [87]:
from sklearn.naive_bayes import MultinomialNB as MB
from sklearn.naive_bayes import GaussianNB as GB

# Multinomial Naive Bayes
classifier_mb = MB()
classifier_mb.fit(train_blogs_matrix,blog_train.Labels)
train_pred_m = classifier_mb.predict(train_blogs_matrix)
accuracy_train_m = np.mean(train_pred_m==blog_train.Labels)
print(accuracy_train_m)

test_pred_m = classifier_mb.predict(test_blogs_matrix)
accuracy_test_m = np.mean(test_pred_m==blog_test.Labels)
print(accuracy_test_m)

0.7214285714285714
0.05

## TFIDF

In [ ]:
# For all blogs
all_blogs_matrix = blogs_bow.transform(blogs_df.Data)
all_blogs_matrix.shape

(2000, 65257)

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer

# Learning Term weighting and normalizing on entire blogs
tfidf_transformer = TfidfTransformer().fit(all_blogs_matrix)

# Preparing TFIDF for train blogs
train_tfidf = tfidf_transformer.transform(train_blogs_matrix)

train_tfidf.shape

# Preparing TFIDF for test blogs
test_tfidf = tfidf_transformer.transform(test_blogs_matrix)

test_tfidf.shape

(600, 65257)

In [ ]:
from sklearn.naive_bayes import MultinomialNB as MB
from sklearn.naive_bayes import GaussianNB as GB

# using tfidf vectorizer
classifier_mb = MB()
classifier_mb.fit(train_tfidf,blog_train.Labels)
train_pred_m = classifier_mb.predict(train_tfidf)
accuracy_train_m = np.mean(train_pred_m==blog_train.Labels)
print(accuracy_train_m)
test_pred_m = classifier_mb.predict(test_tfidf)
accuracy_test_m = np.mean(test_pred_m==blog_test.Labels)
print(accuracy_test_m)

0.87
0.05

The Naive bayes model got the high accuracy value so the we can use this to predict future values.

Text preprocessing is one the main challenge in the classification process.By using several methods like removing text using re module and stop words completes it.